### ISSUE TITLE
Build for Python 3.10 missing

### ISSUE THREAD

**Issue by padix-key** [conda-forge/pymol-open-source-feedstock#16]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

I found that no `pymol-open-source` builds are created for Python 3.10. Am I missing something obvious here or is this some kind of problem with the recipe?

### Installed packages

```shell
N/A
```

### Environment info

```shell
N/A
```

**Comment by bkpoon** [comment]
There is a dependency that is waiting to be migrated for Python 3.10. I made a PR that should fix it, but it is waiting to be merged. I'll try following up again.

https://github.com/conda-forge/pmw-feedstock/pull/17

According to https://conda-forge.org/status/#python310 (click on "in PR" and then search for "pymol"), that should be the last dependency.
